#!/usr/bin/env sh

(echo ".pl 10000i"; \
 echo ".ll 40"; \
    pandoc -fmarkdown -tms $1; \
) |\
  sed 's/\.LP/\.sp/g' |\
  grep -v '^.SH' |\
  sed 's/.PP/.sp/g' |\
  nroff -e -Tutf8 |\
  sed 's/‐/-/g' |\
  cat -s
